height: 200
menubar: false
toolbar:
  - undo redo | blocks | bold italic | alignleft aligncenter alignright | bullist numlist outdent indent | emoticons | removeformat
plugins:
  - insertdatetime lists media table code wordcount emoticons
